import { Element, ElementCategory } from '@/types/element';

export const ELEMENTS: Element[] = [
  // Period 1
  {
    id: 1,
    symbol: 'H',
    name: 'Hydrogen',
    atomicNumber: 1,
    atomicWeight: 1.008,
    category: ElementCategory.NONMETALS,
    period: 1,
    group: 1,
    block: 's',
    electronConfiguration: '1s¹',
    description: 'The lightest and most abundant element in the universe.',
    discoveredBy: 'Henry Cavendish',
    discoveredYear: 1766,
    color: '#FFFFFF',
    phase: 'gas',
    density: 0.08988,
    meltingPoint: -259.16,
    boilingPoint: -252.87,
    electronegativity: 2.20,
    ionizationEnergy: 1312,
    properties: ['Flammable', 'Colorless', 'Odorless', 'Tasteless'],
    uses: ['Fuel', 'Ammonia production', 'Hydrogenation', 'Rocket fuel']
  },
  {
    id: 2,
    symbol: 'He',
    name: 'Helium',
    atomicNumber: 2,
    atomicWeight: 4.003,
    category: ElementCategory.NOBLE_GASES,
    period: 1,
    group: 18,
    block: 's',
    electronConfiguration: '1s²',
    description: 'Second most abundant element in the universe, chemically inert.',
    discoveredBy: 'Pierre Janssen',
    discoveredYear: 1868,
    color: '#D9FFFF',
    phase: 'gas',
    density: 0.1786,
    meltingPoint: -272.2,
    boilingPoint: -268.93,
    properties: ['Inert', 'Colorless', 'Odorless', 'Tasteless'],
    uses: ['Balloons', 'Welding', 'Breathing gas', 'Cryogenics']
  },
  
  // Period 2
  {
    id: 3,
    symbol: 'Li',
    name: 'Lithium',
    atomicNumber: 3,
    atomicWeight: 6.94,
    category: ElementCategory.ALKALI_METALS,
    period: 2,
    group: 1,
    block: 's',
    electronConfiguration: '[He] 2s¹',
    description: 'Lightest metal, used in batteries and mood stabilizers.',
    discoveredBy: 'Johan August Arfwedson',
    discoveredYear: 1817,
    color: '#CC80FF',
    phase: 'solid',
    density: 0.534,
    meltingPoint: 180.5,
    boilingPoint: 1342,
    electronegativity: 0.98,
    ionizationEnergy: 520,
    properties: ['Highly reactive', 'Soft', 'Silvery-white'],
    uses: ['Batteries', 'Ceramics', 'Mood stabilizers', 'Alloys']
  },
  {
    id: 4,
    symbol: 'Be',
    name: 'Beryllium',
    atomicNumber: 4,
    atomicWeight: 9.012,
    category: ElementCategory.ALKALINE_EARTH_METALS,
    period: 2,
    group: 2,
    block: 's',
    electronConfiguration: '[He] 2s²',
    description: 'Steel-gray metal, toxic but useful in aerospace applications.',
    discoveredBy: 'Louis-Nicolas Vauquelin',
    discoveredYear: 1797,
    color: '#C2FF00',
    phase: 'solid',
    density: 1.85,
    meltingPoint: 1287,
    boilingPoint: 2469,
    electronegativity: 1.57,
    ionizationEnergy: 899,
    properties: ['Toxic', 'Hard', 'Brittle', 'Steel-gray'],
    uses: ['Aerospace', 'Nuclear reactors', 'X-ray tubes', 'Alloys']
  },
  {
    id: 5,
    symbol: 'B',
    name: 'Boron',
    atomicNumber: 5,
    atomicWeight: 10.81,
    category: ElementCategory.METALLOIDS,
    period: 2,
    group: 13,
    block: 'p',
    electronConfiguration: '[He] 2s² 2p¹',
    description: 'Metalloid essential for plant growth and nuclear applications.',
    discoveredBy: 'Humphry Davy',
    discoveredYear: 1808,
    color: '#FFB5B5',
    phase: 'solid',
    density: 2.34,
    meltingPoint: 2075,
    boilingPoint: 4000,
    electronegativity: 2.04,
    ionizationEnergy: 801,
    properties: ['Semiconductor', 'Hard', 'Black crystalline'],
    uses: ['Glass', 'Ceramics', 'Nuclear reactors', 'Semiconductors']
  },
  {
    id: 6,
    symbol: 'C',
    name: 'Carbon',
    atomicNumber: 6,
    atomicWeight: 12.011,
    category: ElementCategory.NONMETALS,
    period: 2,
    group: 14,
    block: 'p',
    electronConfiguration: '[He] 2s² 2p²',
    description: 'Basis of all organic chemistry and life on Earth.',
    discoveredBy: 'Ancient civilizations',
    discoveredYear: -3750,
    color: '#909090',
    phase: 'solid',
    density: 2.267,
    meltingPoint: 3550,
    boilingPoint: 4027,
    electronegativity: 2.55,
    ionizationEnergy: 1086,
    properties: ['Tetravalent', 'Catenation', 'Allotropes'],
    uses: ['Steel', 'Plastics', 'Fuels', 'Life processes']
  },
  {
    id: 7,
    symbol: 'N',
    name: 'Nitrogen',
    atomicNumber: 7,
    atomicWeight: 14.007,
    category: ElementCategory.NONMETALS,
    period: 2,
    group: 15,
    block: 'p',
    electronConfiguration: '[He] 2s² 2p³',
    description: 'Essential for proteins and nucleic acids, makes up 78% of air.',
    discoveredBy: 'Daniel Rutherford',
    discoveredYear: 1772,
    color: '#3050F8',
    phase: 'gas',
    density: 1.251,
    meltingPoint: -210.0,
    boilingPoint: -195.8,
    electronegativity: 3.04,
    ionizationEnergy: 1402,
    properties: ['Diatomic', 'Inert', 'Colorless', 'Odorless'],
    uses: ['Fertilizers', 'Explosives', 'Liquid nitrogen', 'Proteins']
  },
  {
    id: 8,
    symbol: 'O',
    name: 'Oxygen',
    atomicNumber: 8,
    atomicWeight: 15.999,
    category: ElementCategory.NONMETALS,
    period: 2,
    group: 16,
    block: 'p',
    electronConfiguration: '[He] 2s² 2p⁴',
    description: 'Essential for respiration and combustion, highly reactive.',
    discoveredBy: 'Carl Wilhelm Scheele',
    discoveredYear: 1774,
    color: '#FF0D0D',
    phase: 'gas',
    density: 1.429,
    meltingPoint: -218.8,
    boilingPoint: -182.9,
    electronegativity: 3.44,
    ionizationEnergy: 1314,
    properties: ['Highly reactive', 'Supports combustion', 'Paramagnetic'],
    uses: ['Respiration', 'Steel production', 'Rocket fuel', 'Medicine']
  },
  {
    id: 9,
    symbol: 'F',
    name: 'Fluorine',
    atomicNumber: 9,
    atomicWeight: 18.998,
    category: ElementCategory.HALOGENS,
    period: 2,
    group: 17,
    block: 'p',
    electronConfiguration: '[He] 2s² 2p⁵',
    description: 'Most electronegative element, highly reactive and toxic.',
    discoveredBy: 'Henri Moissan',
    discoveredYear: 1886,
    color: '#90E050',
    phase: 'gas',
    density: 1.696,
    meltingPoint: -219.7,
    boilingPoint: -188.1,
    electronegativity: 3.98,
    ionizationEnergy: 1681,
    properties: ['Most electronegative', 'Highly reactive', 'Toxic'],
    uses: ['Toothpaste', 'Teflon', 'Refrigerants', 'Uranium enrichment']
  },
  {
    id: 10,
    symbol: 'Ne',
    name: 'Neon',
    atomicNumber: 10,
    atomicWeight: 20.180,
    category: ElementCategory.NOBLE_GASES,
    period: 2,
    group: 18,
    block: 'p',
    electronConfiguration: '[He] 2s² 2p⁶',
    description: 'Noble gas used in lighting and signs.',
    discoveredBy: 'William Ramsay',
    discoveredYear: 1898,
    color: '#B3E3F5',
    phase: 'gas',
    density: 0.9002,
    meltingPoint: -248.6,
    boilingPoint: -246.1,
    properties: ['Inert', 'Colorless', 'Odorless', 'Monatomic'],
    uses: ['Neon signs', 'Lighting', 'Lasers', 'Cryogenics']
  },

  // Period 3
  {
    id: 11,
    symbol: 'Na',
    name: 'Sodium',
    atomicNumber: 11,
    atomicWeight: 22.990,
    category: ElementCategory.ALKALI_METALS,
    period: 3,
    group: 1,
    block: 's',
    electronConfiguration: '[Ne] 3s¹',
    description: 'Soft, silvery-white metal, essential for biological processes.',
    discoveredBy: 'Humphry Davy',
    discoveredYear: 1807,
    color: '#AB5CF2',
    phase: 'solid',
    density: 0.971,
    meltingPoint: 97.8,
    boilingPoint: 883,
    electronegativity: 0.93,
    ionizationEnergy: 496,
    properties: ['Highly reactive', 'Soft', 'Silvery-white'],
    uses: ['Salt', 'Soap', 'Street lamps', 'Coolant']
  },
  {
    id: 12,
    symbol: 'Mg',
    name: 'Magnesium',
    atomicNumber: 12,
    atomicWeight: 24.305,
    category: ElementCategory.ALKALINE_EARTH_METALS,
    period: 3,
    group: 2,
    block: 's',
    electronConfiguration: '[Ne] 3s²',
    description: 'Light, strong metal essential for chlorophyll and bones.',
    discoveredBy: 'Humphry Davy',
    discoveredYear: 1808,
    color: '#8AFF00',
    phase: 'solid',
    density: 1.74,
    meltingPoint: 650,
    boilingPoint: 1090,
    electronegativity: 1.31,
    ionizationEnergy: 738,
    properties: ['Light', 'Strong', 'Silvery-white'],
    uses: ['Alloys', 'Flares', 'Medicine', 'Chlorophyll']
  },
  {
    id: 13,
    symbol: 'Al',
    name: 'Aluminum',
    atomicNumber: 13,
    atomicWeight: 26.982,
    category: ElementCategory.POST_TRANSITION_METALS,
    period: 3,
    group: 13,
    block: 'p',
    electronConfiguration: '[Ne] 3s² 3p¹',
    description: 'Lightweight, corrosion-resistant metal, most abundant metal in Earth\'s crust.',
    discoveredBy: 'Hans Christian Ørsted',
    discoveredYear: 1825,
    color: '#BFA6A6',
    phase: 'solid',
    density: 2.70,
    meltingPoint: 660.3,
    boilingPoint: 2519,
    electronegativity: 1.61,
    ionizationEnergy: 578,
    properties: ['Lightweight', 'Corrosion-resistant', 'Conductive'],
    uses: ['Cans', 'Aircraft', 'Foil', 'Construction']
  },
  {
    id: 14,
    symbol: 'Si',
    name: 'Silicon',
    atomicNumber: 14,
    atomicWeight: 28.085,
    category: ElementCategory.METALLOIDS,
    period: 3,
    group: 14,
    block: 'p',
    electronConfiguration: '[Ne] 3s² 3p²',
    description: 'Metalloid essential for electronics and computer chips.',
    discoveredBy: 'Jöns Jacob Berzelius',
    discoveredYear: 1824,
    color: '#F0C8A0',
    phase: 'solid',
    density: 2.33,
    meltingPoint: 1414,
    boilingPoint: 3265,
    electronegativity: 1.90,
    ionizationEnergy: 787,
    properties: ['Semiconductor', 'Hard', 'Brittle'],
    uses: ['Computer chips', 'Glass', 'Solar panels', 'Silicone']
  },
  {
    id: 15,
    symbol: 'P',
    name: 'Phosphorus',
    atomicNumber: 15,
    atomicWeight: 30.974,
    category: ElementCategory.NONMETALS,
    period: 3,
    group: 15,
    block: 'p',
    electronConfiguration: '[Ne] 3s² 3p³',
    description: 'Essential for DNA, RNA, and ATP, exists in multiple allotropes.',
    discoveredBy: 'Hennig Brand',
    discoveredYear: 1669,
    color: '#FF8000',
    phase: 'solid',
    density: 1.82,
    meltingPoint: 44.2,
    boilingPoint: 280.5,
    electronegativity: 2.19,
    ionizationEnergy: 1012,
    properties: ['Multiple allotropes', 'Essential for life', 'Reactive'],
    uses: ['Fertilizers', 'Matches', 'Detergents', 'DNA/RNA']
  },
  {
    id: 16,
    symbol: 'S',
    name: 'Sulfur',
    atomicNumber: 16,
    atomicWeight: 32.06,
    category: ElementCategory.NONMETALS,
    period: 3,
    group: 16,
    block: 'p',
    electronConfiguration: '[Ne] 3s² 3p⁴',
    description: 'Yellow crystalline solid, essential for proteins and vulcanization.',
    discoveredBy: 'Ancient civilizations',
    discoveredYear: -2000,
    color: '#FFFF30',
    phase: 'solid',
    density: 2.07,
    meltingPoint: 115.2,
    boilingPoint: 444.6,
    electronegativity: 2.58,
    ionizationEnergy: 1000,
    properties: ['Yellow', 'Crystalline', 'Multiple allotropes'],
    uses: ['Sulfuric acid', 'Vulcanization', 'Fertilizers', 'Gunpowder']
  },
  {
    id: 17,
    symbol: 'Cl',
    name: 'Chlorine',
    atomicNumber: 17,
    atomicWeight: 35.45,
    category: ElementCategory.HALOGENS,
    period: 3,
    group: 17,
    block: 'p',
    electronConfiguration: '[Ne] 3s² 3p⁵',
    description: 'Poisonous gas used for disinfection and bleaching.',
    discoveredBy: 'Carl Wilhelm Scheele',
    discoveredYear: 1774,
    color: '#1FF01F',
    phase: 'gas',
    density: 3.214,
    meltingPoint: -101.5,
    boilingPoint: -34.0,
    electronegativity: 3.16,
    ionizationEnergy: 1251,
    properties: ['Toxic', 'Greenish-yellow', 'Diatomic'],
    uses: ['Disinfection', 'Bleach', 'PVC', 'Salt']
  },
  {
    id: 18,
    symbol: 'Ar',
    name: 'Argon',
    atomicNumber: 18,
    atomicWeight: 39.948,
    category: ElementCategory.NOBLE_GASES,
    period: 3,
    group: 18,
    block: 'p',
    electronConfiguration: '[Ne] 3s² 3p⁶',
    description: 'Third most abundant gas in Earth\'s atmosphere, chemically inert.',
    discoveredBy: 'Lord Rayleigh',
    discoveredYear: 1894,
    color: '#80D1E3',
    phase: 'gas',
    density: 1.784,
    meltingPoint: -189.3,
    boilingPoint: -185.8,
    properties: ['Inert', 'Colorless', 'Odorless', 'Monatomic'],
    uses: ['Welding', 'Light bulbs', 'Lasers', 'Preservation']
  },

  // Period 4
  {
    id: 19,
    symbol: 'K',
    name: 'Potassium',
    atomicNumber: 19,
    atomicWeight: 39.098,
    category: ElementCategory.ALKALI_METALS,
    period: 4,
    group: 1,
    block: 's',
    electronConfiguration: '[Ar] 4s¹',
    description: 'Soft, silvery-white metal essential for biological processes.',
    discoveredBy: 'Humphry Davy',
    discoveredYear: 1807,
    color: '#8F40D4',
    phase: 'solid',
    density: 0.862,
    meltingPoint: 63.5,
    boilingPoint: 759,
    electronegativity: 0.82,
    ionizationEnergy: 419,
    properties: ['Highly reactive', 'Soft', 'Silvery-white'],
    uses: ['Fertilizers', 'Soap', 'Glass', 'Gunpowder']
  },
  {
    id: 20,
    symbol: 'Ca',
    name: 'Calcium',
    atomicNumber: 20,
    atomicWeight: 40.078,
    category: ElementCategory.ALKALINE_EARTH_METALS,
    period: 4,
    group: 2,
    block: 's',
    electronConfiguration: '[Ar] 4s²',
    description: 'Essential for bones and teeth, fifth most abundant element.',
    discoveredBy: 'Humphry Davy',
    discoveredYear: 1808,
    color: '#3DFF00',
    phase: 'solid',
    density: 1.54,
    meltingPoint: 842,
    boilingPoint: 1484,
    electronegativity: 1.00,
    ionizationEnergy: 590,
    properties: ['Reactive', 'Silvery-white', 'Soft'],
    uses: ['Bones', 'Cement', 'Cheese', 'Plaster']
  },
  {
    id: 21,
    symbol: 'Sc',
    name: 'Scandium',
    atomicNumber: 21,
    atomicWeight: 44.956,
    category: ElementCategory.TRANSITION_METALS,
    period: 4,
    group: 3,
    block: 'd',
    electronConfiguration: '[Ar] 3d¹ 4s²',
    description: 'Rare earth metal used in aerospace and sports equipment.',
    discoveredBy: 'Lars Fredrik Nilson',
    discoveredYear: 1879,
    color: '#E6E6E6',
    phase: 'solid',
    density: 2.99,
    meltingPoint: 1541,
    boilingPoint: 2836,
    electronegativity: 1.36,
    ionizationEnergy: 633,
    properties: ['Rare', 'Silvery-white', 'Lightweight'],
    uses: ['Aerospace', 'Sports equipment', 'Lighting', 'Fuel cells']
  },
  {
    id: 22,
    symbol: 'Ti',
    name: 'Titanium',
    atomicNumber: 22,
    atomicWeight: 47.867,
    category: ElementCategory.TRANSITION_METALS,
    period: 4,
    group: 4,
    block: 'd',
    electronConfiguration: '[Ar] 3d² 4s²',
    description: 'Strong, lightweight, corrosion-resistant metal.',
    discoveredBy: 'William Gregor',
    discoveredYear: 1791,
    color: '#BFC2C7',
    phase: 'solid',
    density: 4.54,
    meltingPoint: 1668,
    boilingPoint: 3287,
    electronegativity: 1.54,
    ionizationEnergy: 658,
    properties: ['Strong', 'Lightweight', 'Corrosion-resistant'],
    uses: ['Aerospace', 'Medical implants', 'Jewelry', 'Pigments']
  },
  {
    id: 23,
    symbol: 'V',
    name: 'Vanadium',
    atomicNumber: 23,
    atomicWeight: 50.942,
    category: ElementCategory.TRANSITION_METALS,
    period: 4,
    group: 5,
    block: 'd',
    electronConfiguration: '[Ar] 3d³ 4s²',
    description: 'Hard, silvery-gray metal used in steel alloys.',
    discoveredBy: 'Andrés Manuel del Río',
    discoveredYear: 1801,
    color: '#A6A6AB',
    phase: 'solid',
    density: 6.11,
    meltingPoint: 1910,
    boilingPoint: 3407,
    electronegativity: 1.63,
    ionizationEnergy: 651,
    properties: ['Hard', 'Silvery-gray', 'Ductile'],
    uses: ['Steel alloys', 'Tools', 'Springs', 'Catalysts']
  },
  {
    id: 24,
    symbol: 'Cr',
    name: 'Chromium',
    atomicNumber: 24,
    atomicWeight: 51.996,
    category: ElementCategory.TRANSITION_METALS,
    period: 4,
    group: 6,
    block: 'd',
    electronConfiguration: '[Ar] 3d⁵ 4s¹',
    description: 'Hard, steel-gray metal used for chrome plating.',
    discoveredBy: 'Louis Nicolas Vauquelin',
    discoveredYear: 1797,
    color: '#8A99C7',
    phase: 'solid',
    density: 7.15,
    meltingPoint: 1907,
    boilingPoint: 2671,
    electronegativity: 1.66,
    ionizationEnergy: 653,
    properties: ['Hard', 'Steel-gray', 'Brittle'],
    uses: ['Chrome plating', 'Stainless steel', 'Pigments', 'Leather tanning']
  },
  {
    id: 25,
    symbol: 'Mn',
    name: 'Manganese',
    atomicNumber: 25,
    atomicWeight: 54.938,
    category: ElementCategory.TRANSITION_METALS,
    period: 4,
    group: 7,
    block: 'd',
    electronConfiguration: '[Ar] 3d⁵ 4s²',
    description: 'Essential for steel production and biological processes.',
    discoveredBy: 'Carl Wilhelm Scheele',
    discoveredYear: 1774,
    color: '#9C7AC7',
    phase: 'solid',
    density: 7.44,
    meltingPoint: 1246,
    boilingPoint: 2061,
    electronegativity: 1.55,
    ionizationEnergy: 717,
    properties: ['Hard', 'Brittle', 'Gray-white'],
    uses: ['Steel production', 'Batteries', 'Fertilizers', 'Gasoline additive']
  },
  {
    id: 26,
    symbol: 'Fe',
    name: 'Iron',
    atomicNumber: 26,
    atomicWeight: 55.845,
    category: ElementCategory.TRANSITION_METALS,
    period: 4,
    group: 8,
    block: 'd',
    electronConfiguration: '[Ar] 3d⁶ 4s²',
    description: 'Most abundant metal on Earth, essential for blood and steel.',
    discoveredBy: 'Ancient civilizations',
    discoveredYear: -5000,
    color: '#E06633',
    phase: 'solid',
    density: 7.87,
    meltingPoint: 1538,
    boilingPoint: 2861,
    electronegativity: 1.83,
    ionizationEnergy: 762,
    properties: ['Magnetic', 'Malleable', 'Ductile'],
    uses: ['Steel', 'Hemoglobin', 'Tools', 'Construction']
  },
  {
    id: 27,
    symbol: 'Co',
    name: 'Cobalt',
    atomicNumber: 27,
    atomicWeight: 58.933,
    category: ElementCategory.TRANSITION_METALS,
    period: 4,
    group: 9,
    block: 'd',
    electronConfiguration: '[Ar] 3d⁷ 4s²',
    description: 'Hard, lustrous metal used in superalloys and batteries.',
    discoveredBy: 'Georg Brandt',
    discoveredYear: 1735,
    color: '#F090A0',
    phase: 'solid',
    density: 8.86,
    meltingPoint: 1495,
    boilingPoint: 2927,
    electronegativity: 1.88,
    ionizationEnergy: 760,
    properties: ['Hard', 'Lustrous', 'Ferromagnetic'],
    uses: ['Superalloys', 'Batteries', 'Magnets', 'Catalysts']
  },
  {
    id: 28,
    symbol: 'Ni',
    name: 'Nickel',
    atomicNumber: 28,
    atomicWeight: 58.693,
    category: ElementCategory.TRANSITION_METALS,
    period: 4,
    group: 10,
    block: 'd',
    electronConfiguration: '[Ar] 3d⁸ 4s²',
    description: 'Silvery-white metal used in coins and stainless steel.',
    discoveredBy: 'Axel Fredrik Cronstedt',
    discoveredYear: 1751,
    color: '#50D050',
    phase: 'solid',
    density: 8.91,
    meltingPoint: 1455,
    boilingPoint: 2913,
    electronegativity: 1.91,
    ionizationEnergy: 737,
    properties: ['Silvery-white', 'Hard', 'Malleable'],
    uses: ['Coins', 'Stainless steel', 'Batteries', 'Plating']
  },
  {
    id: 29,
    symbol: 'Cu',
    name: 'Copper',
    atomicNumber: 29,
    atomicWeight: 63.546,
    category: ElementCategory.TRANSITION_METALS,
    period: 4,
    group: 11,
    block: 'd',
    electronConfiguration: '[Ar] 3d¹⁰ 4s¹',
    description: 'Reddish-brown metal, excellent conductor of electricity.',
    discoveredBy: 'Ancient civilizations',
    discoveredYear: -9000,
    color: '#C88033',
    phase: 'solid',
    density: 8.96,
    meltingPoint: 1085,
    boilingPoint: 2562,
    electronegativity: 1.90,
    ionizationEnergy: 745,
    properties: ['Excellent conductor', 'Reddish-brown', 'Malleable'],
    uses: ['Electrical wiring', 'Plumbing', 'Coins', 'Bronze']
  },
  {
    id: 30,
    symbol: 'Zn',
    name: 'Zinc',
    atomicNumber: 30,
    atomicWeight: 65.38,
    category: ElementCategory.TRANSITION_METALS,
    period: 4,
    group: 12,
    block: 'd',
    electronConfiguration: '[Ar] 3d¹⁰ 4s²',
    description: 'Bluish-white metal used for galvanization and brass.',
    discoveredBy: 'Ancient civilizations',
    discoveredYear: -1000,
    color: '#7D80B0',
    phase: 'solid',
    density: 7.13,
    meltingPoint: 419.5,
    boilingPoint: 907,
    electronegativity: 1.65,
    ionizationEnergy: 906,
    properties: ['Bluish-white', 'Brittle', 'Malleable when heated'],
    uses: ['Galvanization', 'Brass', 'Batteries', 'Dietary supplement']
  },
  {
    id: 31,
    symbol: 'Ga',
    name: 'Gallium',
    atomicNumber: 31,
    atomicWeight: 69.723,
    category: ElementCategory.POST_TRANSITION_METALS,
    period: 4,
    group: 13,
    block: 'p',
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p¹',
    description: 'Soft, silvery metal that melts at room temperature.',
    discoveredBy: 'Paul-Émile Lecoq de Boisbaudran',
    discoveredYear: 1875,
    color: '#C28F8F',
    phase: 'solid',
    density: 5.91,
    meltingPoint: 29.8,
    boilingPoint: 2204,
    electronegativity: 1.81,
    ionizationEnergy: 579,
    properties: ['Soft', 'Silvery', 'Low melting point'],
    uses: ['Semiconductors', 'LEDs', 'Solar panels', 'Thermometers']
  },
  {
    id: 32,
    symbol: 'Ge',
    name: 'Germanium',
    atomicNumber: 32,
    atomicWeight: 72.630,
    category: ElementCategory.METALLOIDS,
    period: 4,
    group: 14,
    block: 'p',
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p²',
    description: 'Lustrous metalloid used in semiconductors and fiber optics.',
    discoveredBy: 'Clemens Winkler',
    discoveredYear: 1886,
    color: '#668F8F',
    phase: 'solid',
    density: 5.32,
    meltingPoint: 938.3,
    boilingPoint: 2833,
    electronegativity: 2.01,
    ionizationEnergy: 762,
    properties: ['Lustrous', 'Hard', 'Brittle'],
    uses: ['Semiconductors', 'Fiber optics', 'Infrared optics', 'Catalysts']
  },
  {
    id: 33,
    symbol: 'As',
    name: 'Arsenic',
    atomicNumber: 33,
    atomicWeight: 74.922,
    category: ElementCategory.METALLOIDS,
    period: 4,
    group: 15,
    block: 'p',
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p³',
    description: 'Toxic metalloid used in semiconductors and pesticides.',
    discoveredBy: 'Ancient civilizations',
    discoveredYear: -500,
    color: '#BD80E3',
    phase: 'solid',
    density: 5.73,
    meltingPoint: 817,
    boilingPoint: 614,
    electronegativity: 2.18,
    ionizationEnergy: 947,
    properties: ['Toxic', 'Brittle', 'Silvery-gray'],
    uses: ['Semiconductors', 'Pesticides', 'Wood preservatives', 'Alloys']
  },
  {
    id: 34,
    symbol: 'Se',
    name: 'Selenium',
    atomicNumber: 34,
    atomicWeight: 78.971,
    category: ElementCategory.NONMETALS,
    period: 4,
    group: 16,
    block: 'p',
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁴',
    description: 'Nonmetal essential for biological processes and photoconductivity.',
    discoveredBy: 'Jöns Jacob Berzelius',
    discoveredYear: 1817,
    color: '#FFA100',
    phase: 'solid',
    density: 4.81,
    meltingPoint: 221,
    boilingPoint: 685,
    electronegativity: 2.55,
    ionizationEnergy: 941,
    properties: ['Photoconductor', 'Essential nutrient', 'Multiple allotropes'],
    uses: ['Photocells', 'Xerography', 'Glass decolorizer', 'Antioxidant']
  },
  {
    id: 35,
    symbol: 'Br',
    name: 'Bromine',
    atomicNumber: 35,
    atomicWeight: 79.904,
    category: ElementCategory.HALOGENS,
    period: 4,
    group: 17,
    block: 'p',
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁵',
    description: 'Reddish-brown liquid at room temperature, toxic and corrosive.',
    discoveredBy: 'Antoine Jérôme Balard',
    discoveredYear: 1826,
    color: '#A62929',
    phase: 'liquid',
    density: 3.12,
    meltingPoint: -7.2,
    boilingPoint: 58.8,
    electronegativity: 2.96,
    ionizationEnergy: 1140,
    properties: ['Reddish-brown', 'Volatile', 'Corrosive'],
    uses: ['Flame retardants', 'Pesticides', 'Dyes', 'Photography']
  },
  {
    id: 36,
    symbol: 'Kr',
    name: 'Krypton',
    atomicNumber: 36,
    atomicWeight: 83.798,
    category: ElementCategory.NOBLE_GASES,
    period: 4,
    group: 18,
    block: 'p',
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁶',
    description: 'Noble gas used in high-performance light bulbs.',
    discoveredBy: 'William Ramsay',
    discoveredYear: 1898,
    color: '#5CB8D1',
    phase: 'gas',
    density: 3.733,
    meltingPoint: -157.4,
    boilingPoint: -153.2,
    properties: ['Inert', 'Colorless', 'Odorless', 'Monatomic'],
    uses: ['High-performance bulbs', 'Lasers', 'Photography', 'Insulation']
  },

  // Period 5 elements (37-54)
  {
    id: 37,
    symbol: 'Rb',
    name: 'Rubidium',
    atomicNumber: 37,
    atomicWeight: 85.468,
    category: ElementCategory.ALKALI_METALS,
    period: 5,
    group: 1,
    block: 's',
    electronConfiguration: '[Kr] 5s¹',
    description: 'Soft, silvery-white metal, highly reactive.',
    discoveredBy: 'Robert Bunsen',
    discoveredYear: 1861,
    color: '#702EB0',
    phase: 'solid',
    density: 1.53,
    meltingPoint: 39.3,
    boilingPoint: 688,
    electronegativity: 0.82,
    ionizationEnergy: 403,
    properties: ['Highly reactive', 'Soft', 'Silvery-white'],
    uses: ['Atomic clocks', 'Photocells', 'Catalysts', 'Specialty glass']
  },
  {
    id: 38,
    symbol: 'Sr',
    name: 'Strontium',
    atomicNumber: 38,
    atomicWeight: 87.62,
    category: ElementCategory.ALKALINE_EARTH_METALS,
    period: 5,
    group: 2,
    block: 's',
    electronConfiguration: '[Kr] 5s²',
    description: 'Soft, silvery-white metal used in fireworks and magnets.',
    discoveredBy: 'William Cruickshank',
    discoveredYear: 1790,
    color: '#00FF00',
    phase: 'solid',
    density: 2.64,
    meltingPoint: 777,
    boilingPoint: 1382,
    electronegativity: 0.95,
    ionizationEnergy: 549,
    properties: ['Soft', 'Silvery-white', 'Reactive'],
    uses: ['Fireworks', 'Magnets', 'Bone implants', 'Toothpaste']
  },
  {
    id: 39,
    symbol: 'Y',
    name: 'Yttrium',
    atomicNumber: 39,
    atomicWeight: 88.90585,
    category: ElementCategory.TRANSITION_METALS,
    period: 5,
    group: 3,
    block: 'd',
    electronConfiguration: '[Kr] 4d¹ 5s²',
    description: 'Silvery-metallic transition metal used in superconductors.',
    discoveredBy: 'Johan Gadolin',
    discoveredYear: 1794,
    color: '#94FFFF',
    phase: 'solid',
    density: 4.47,
    meltingPoint: 1526,
    boilingPoint: 3203,
    electronegativity: 1.22,
    ionizationEnergy: 600,
    properties: ['Silvery-metallic', 'Hard', 'Stable'],
    uses: ['Superconductors', 'Lasers', 'Alloys', 'Phosphors']
  },
  {
    id: 40,
    symbol: 'Zr',
    name: 'Zirconium',
    atomicNumber: 40,
    atomicWeight: 91.224,
    category: ElementCategory.TRANSITION_METALS,
    period: 5,
    group: 4,
    block: 'd',
    electronConfiguration: '[Kr] 4d² 5s²',
    description: 'Lustrous, greyish-white metal used in nuclear reactors.',
    discoveredBy: 'Martin Heinrich Klaproth',
    discoveredYear: 1789,
    color: '#94E0E0',
    phase: 'solid',
    density: 6.51,
    meltingPoint: 1855,
    boilingPoint: 4409,
    electronegativity: 1.33,
    ionizationEnergy: 640,
    properties: ['Corrosion-resistant', 'Strong', 'Lustrous'],
    uses: ['Nuclear reactors', 'Alloys', 'Refractories', 'Abrasives']
  },
  {
    id: 41,
    symbol: 'Nb',
    name: 'Niobium',
    atomicNumber: 41,
    atomicWeight: 92.90638,
    category: ElementCategory.TRANSITION_METALS,
    period: 5,
    group: 5,
    block: 'd',
    electronConfiguration: '[Kr] 4d⁴ 5s¹',
    description: 'Soft, grey metal used in superconducting magnets.',
    discoveredBy: 'Charles Hatchett',
    discoveredYear: 1801,
    color: '#73C2C9',
    phase: 'solid',
    density: 8.57,
    meltingPoint: 2477,
    boilingPoint: 4744,
    electronegativity: 1.6,
    ionizationEnergy: 652,
    properties: ['Soft', 'Grey', 'Superconducting'],
    uses: ['Superconducting magnets', 'Steel alloys', 'Jet engines', 'Jewelry']
  },
  {
    id: 42,
    symbol: 'Mo',
    name: 'Molybdenum',
    atomicNumber: 42,
    atomicWeight: 95.95,
    category: ElementCategory.TRANSITION_METALS,
    period: 5,
    group: 6,
    block: 'd',
    electronConfiguration: '[Kr] 4d⁵ 5s¹',
    description: 'Silvery metal with high melting point used in alloys.',
    discoveredBy: 'Carl Wilhelm Scheele',
    discoveredYear: 1778,
    color: '#54B5B5',
    phase: 'solid',
    density: 10.28,
    meltingPoint: 2623,
    boilingPoint: 4639,
    electronegativity: 2.16,
    ionizationEnergy: 684,
    properties: ['High melting point', 'Hard', 'Silvery'],
    uses: ['Steel alloys', 'Catalysts', 'Lubricants', 'Armor plating']
  },
  {
    id: 43,
    symbol: 'Tc',
    name: 'Technetium',
    atomicNumber: 43,
    atomicWeight: 98,
    category: ElementCategory.TRANSITION_METALS,
    period: 5,
    group: 7,
    block: 'd',
    electronConfiguration: '[Kr] 4d⁵ 5s²',
    description: 'Radioactive metal, the first artificially produced element.',
    discoveredBy: 'Emilio Segrè',
    discoveredYear: 1937,
    color: '#3B9E9E',
    phase: 'solid',
    density: 11,
    meltingPoint: 2157,
    boilingPoint: 4265,
    electronegativity: 1.9,
    ionizationEnergy: 702,
    properties: ['Radioactive', 'Synthetic', 'Silvery-grey'],
    uses: ['Medical imaging', 'Nuclear medicine', 'Corrosion inhibitor', 'Research']
  },
  {
    id: 44,
    symbol: 'Ru',
    name: 'Ruthenium',
    atomicNumber: 44,
    atomicWeight: 101.07,
    category: ElementCategory.TRANSITION_METALS,
    period: 5,
    group: 8,
    block: 'd',
    electronConfiguration: '[Kr] 4d⁷ 5s¹',
    description: 'Rare, hard, silvery-white metal of the platinum group.',
    discoveredBy: 'Karl Ernst Claus',
    discoveredYear: 1844,
    color: '#248F8F',
    phase: 'solid',
    density: 12.45,
    meltingPoint: 2334,
    boilingPoint: 4150,
    electronegativity: 2.2,
    ionizationEnergy: 710,
    properties: ['Rare', 'Hard', 'Platinum group'],
    uses: ['Catalysts', 'Electronics', 'Alloys', 'Jewelry']
  },
  {
    id: 45,
    symbol: 'Rh',
    name: 'Rhodium',
    atomicNumber: 45,
    atomicWeight: 102.9055,
    category: ElementCategory.TRANSITION_METALS,
    period: 5,
    group: 9,
    block: 'd',
    electronConfiguration: '[Kr] 4d⁸ 5s¹',
    description: 'Rare, silvery-white metal used in catalytic converters.',
    discoveredBy: 'William Hyde Wollaston',
    discoveredYear: 1803,
    color: '#0A7D8C',
    phase: 'solid',
    density: 12.41,
    meltingPoint: 1964,
    boilingPoint: 3695,
    electronegativity: 2.28,
    ionizationEnergy: 719,
    properties: ['Rare', 'Silvery-white', 'Corrosion-resistant'],
    uses: ['Catalytic converters', 'Jewelry', 'Laboratory equipment', 'Mirrors']
  },
  {
    id: 46,
    symbol: 'Pd',
    name: 'Palladium',
    atomicNumber: 46,
    atomicWeight: 106.42,
    category: ElementCategory.TRANSITION_METALS,
    period: 5,
    group: 10,
    block: 'd',
    electronConfiguration: '[Kr] 4d¹⁰',
    description: 'Rare, lustrous silvery-white metal used in catalysts.',
    discoveredBy: 'William Hyde Wollaston',
    discoveredYear: 1803,
    color: '#006985',
    phase: 'solid',
    density: 12.023,
    meltingPoint: 1554.9,
    boilingPoint: 2963,
    electronegativity: 2.2,
    ionizationEnergy: 804,
    properties: ['Lustrous', 'Silvery-white', 'Ductile'],
    uses: ['Catalysts', 'Electronics', 'Jewelry', 'Dentistry']
  },
  {
    id: 47,
    symbol: 'Ag',
    name: 'Silver',
    atomicNumber: 47,
    atomicWeight: 107.8682,
    category: ElementCategory.TRANSITION_METALS,
    period: 5,
    group: 11,
    block: 'd',
    electronConfiguration: '[Kr] 4d¹⁰ 5s¹',
    description: 'Lustrous white metal with highest electrical conductivity.',
    discoveredBy: 'Ancient civilizations',
    discoveredYear: -3000,
    color: '#C0C0C0',
    phase: 'solid',
    density: 10.49,
    meltingPoint: 961.78,
    boilingPoint: 2162,
    electronegativity: 1.93,
    ionizationEnergy: 731,
    properties: ['Lustrous', 'Conductive', 'Malleable'],
    uses: ['Jewelry', 'Electronics', 'Photography', 'Antibacterial']
  },
  {
    id: 48,
    symbol: 'Cd',
    name: 'Cadmium',
    atomicNumber: 48,
    atomicWeight: 112.411,
    category: ElementCategory.TRANSITION_METALS,
    period: 5,
    group: 12,
    block: 'd',
    electronConfiguration: '[Kr] 4d¹⁰ 5s²',
    description: 'Soft, bluish-white metal used in batteries and pigments.',
    discoveredBy: 'Karl Samuel Leberecht Hermann',
    discoveredYear: 1817,
    color: '#FFD98F',
    phase: 'solid',
    density: 8.65,
    meltingPoint: 321.07,
    boilingPoint: 767,
    electronegativity: 1.69,
    ionizationEnergy: 867,
    properties: ['Soft', 'Bluish-white', 'Toxic'],
    uses: ['Batteries', 'Pigments', 'Coatings', 'Alloys']
  },
  {
    id: 49,
    symbol: 'In',
    name: 'Indium',
    atomicNumber: 49,
    atomicWeight: 114.818,
    category: ElementCategory.POST_TRANSITION_METALS,
    period: 5,
    group: 13,
    block: 'p',
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p¹',
    description: 'Soft, silvery-white metal used in touchscreens.',
    discoveredBy: 'Ferdinand Reich',
    discoveredYear: 1863,
    color: '#A67573',
    phase: 'solid',
    density: 7.31,
    meltingPoint: 156.6,
    boilingPoint: 2072,
    electronegativity: 1.78,
    ionizationEnergy: 558,
    properties: ['Soft', 'Silvery-white', 'Malleable'],
    uses: ['Touchscreens', 'Solar cells', 'LEDs', 'Alloys']
  },
  {
    id: 50,
    symbol: 'Sn',
    name: 'Tin',
    atomicNumber: 50,
    atomicWeight: 118.71,
    category: ElementCategory.POST_TRANSITION_METALS,
    period: 5,
    group: 14,
    block: 'p',
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p²',
    description: 'Silvery-white metal used in alloys and coatings.',
    discoveredBy: 'Ancient civilizations',
    discoveredYear: -3500,
    color: '#668F8F',
    phase: 'solid',
    density: 7.287,
    meltingPoint: 231.93,
    boilingPoint: 2602,
    electronegativity: 1.96,
    ionizationEnergy: 708,
    properties: ['Silvery-white', 'Malleable', 'Crystalline'],
    uses: ['Alloys', 'Coatings', 'Soldering', 'Cans']
  },
  {
    id: 51,
    symbol: 'Sb',
    name: 'Antimony',
    atomicNumber: 51,
    atomicWeight: 121.76,
    category: ElementCategory.METALLOIDS,
    period: 5,
    group: 15,
    block: 'p',
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p³',
    description: 'Lustrous grey metalloid used in flame retardants.',
    discoveredBy: 'Ancient civilizations',
    discoveredYear: -1600,
    color: '#9E63B5',
    phase: 'solid',
    density: 6.697,
    meltingPoint: 630.63,
    boilingPoint: 1587,
    electronegativity: 2.05,
    ionizationEnergy: 834,
    properties: ['Lustrous', 'Grey', 'Brittle'],
    uses: ['Flame retardants', 'Alloys', 'Semiconductors', 'Cosmetics']
  },
  {
    id: 52,
    symbol: 'Te',
    name: 'Tellurium',
    atomicNumber: 52,
    atomicWeight: 127.6,
    category: ElementCategory.METALLOIDS,
    period: 5,
    group: 16,
    block: 'p',
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁴',
    description: 'Brittle, silvery-white metalloid used in alloys.',
    discoveredBy: 'Franz-Joseph Müller von Reichenstein',
    discoveredYear: 1782,
    color: '#D47A00',
    phase: 'solid',
    density: 6.24,
    meltingPoint: 449.51,
    boilingPoint: 988,
    electronegativity: 2.1,
    ionizationEnergy: 869,
    properties: ['Brittle', 'Silvery-white', 'Semiconducting'],
    uses: ['Alloys', 'Solar cells', 'Catalysts', 'Rubber vulcanization']
  },
  {
    id: 53,
    symbol: 'I',
    name: 'Iodine',
    atomicNumber: 53,
    atomicWeight: 126.90447,
    category: ElementCategory.HALOGENS,
    period: 5,
    group: 17,
    block: 'p',
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁵',
    description: 'Lustrous, purple-black halogen used in medicine.',
    discoveredBy: 'Bernard Courtois',
    discoveredYear: 1811,
    color: '#940094',
    phase: 'solid',
    density: 4.933,
    meltingPoint: 113.7,
    boilingPoint: 184.3,
    electronegativity: 2.66,
    ionizationEnergy: 1008,
    properties: ['Lustrous', 'Purple-black', 'Volatile'],
    uses: ['Medicine', 'Photography', 'Disinfectants', 'Dyes']
  },
  {
    id: 54,
    symbol: 'Xe',
    name: 'Xenon',
    atomicNumber: 54,
    atomicWeight: 131.293,
    category: ElementCategory.NOBLE_GASES,
    period: 5,
    group: 18,
    block: 'p',
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁶',
    description: 'Colorless, odorless noble gas used in lighting.',
    discoveredBy: 'William Ramsay',
    discoveredYear: 1898,
    color: '#429EB0',
    phase: 'gas',
    density: 5.894,
    meltingPoint: -111.75,
    boilingPoint: -108.099,
    electronegativity: 2.6,
    ionizationEnergy: 1170,
    properties: ['Colorless', 'Odorless', 'Inert'],
    uses: ['Lighting', 'Anesthesia', 'Ion propulsion', 'Lasers']
  },

  // Period 6 key elements
  {
    id: 55,
    symbol: 'Cs',
    name: 'Cesium',
    atomicNumber: 55,
    atomicWeight: 132.91,
    category: ElementCategory.ALKALI_METALS,
    period: 6,
    group: 1,
    block: 's',
    electronConfiguration: '[Xe] 6s¹',
    description: 'Soft, silvery-gold metal, most electropositive element.',
    discoveredBy: 'Robert Bunsen',
    discoveredYear: 1860,
    color: '#57178F',
    phase: 'solid',
    density: 1.93,
    meltingPoint: 28.4,
    boilingPoint: 671,
    electronegativity: 0.79,
    ionizationEnergy: 376,
    properties: ['Most electropositive', 'Soft', 'Silvery-gold'],
    uses: ['Atomic clocks', 'Photoelectric cells', 'Catalysts', 'Drilling fluids']
  },
  {
    id: 56,
    symbol: 'Ba',
    name: 'Barium',
    atomicNumber: 56,
    atomicWeight: 137.33,
    category: ElementCategory.ALKALINE_EARTH_METALS,
    period: 6,
    group: 2,
    block: 's',
    electronConfiguration: '[Xe] 6s²',
    description: 'Soft, silvery-white metal used in X-ray imaging.',
    discoveredBy: 'Humphry Davy',
    discoveredYear: 1808,
    color: '#00C900',
    phase: 'solid',
    density: 3.62,
    meltingPoint: 727,
    boilingPoint: 1870,
    electronegativity: 0.89,
    ionizationEnergy: 503,
    properties: ['Soft', 'Silvery-white', 'Reactive'],
    uses: ['X-ray imaging', 'Drilling mud', 'Fireworks', 'Rat poison']
  },
  {
    id: 57,
    symbol: 'La',
    name: 'Lanthanum',
    atomicNumber: 57,
    atomicWeight: 138.9055,
    category: ElementCategory.LANTHANIDES,
    period: 6,
    group: 3,
    block: 'd',
    electronConfiguration: '[Xe] 5d¹ 6s²',
    description: 'Soft, ductile, silvery-white lanthanide metal.',
    discoveredBy: 'Carl Gustaf Mosander',
    discoveredYear: 1839,
    color: '#70D4FF',
    phase: 'solid',
    density: 6.15,
    meltingPoint: 920,
    boilingPoint: 3464,
    electronegativity: 1.1,
    ionizationEnergy: 538,
    properties: ['Soft', 'Ductile', 'Silvery-white'],
    uses: ['Catalysts', 'Alloys', 'Optical glasses', 'Hydrogen storage']
  },
  {
    id: 58,
    symbol: 'Ce',
    name: 'Cerium',
    atomicNumber: 58,
    atomicWeight: 140.116,
    category: ElementCategory.LANTHANIDES,
    period: 6,
    group: 3,
    block: 'f',
    electronConfiguration: '[Xe] 4f¹ 5d¹ 6s²',
    description: 'Soft, ductile, silvery-white lanthanide metal.',
    discoveredBy: 'Jöns Jacob Berzelius',
    discoveredYear: 1803,
    color: '#FFFFC7',
    phase: 'solid',
    density: 6.77,
    meltingPoint: 798,
    boilingPoint: 3443,
    electronegativity: 1.12,
    ionizationEnergy: 534,
    properties: ['Soft', 'Ductile', 'Tarnishes slowly'],
    uses: ['Catalysts', 'Lighter flints', 'Glass polishing', 'Alloys']
  },
  {
    id: 59,
    symbol: 'Pr',
    name: 'Praseodymium',
    atomicNumber: 59,
    atomicWeight: 140.90765,
    category: ElementCategory.LANTHANIDES,
    period: 6,
    group: 3,
    block: 'f',
    electronConfiguration: '[Xe] 4f³ 6s²',
    description: 'Soft, silvery lanthanide metal that develops a green oxide coating.',
    discoveredBy: 'Carl Auer von Welsbach',
    discoveredYear: 1885,
    color: '#D9FFC7',
    phase: 'solid',
    density: 6.77,
    meltingPoint: 931,
    boilingPoint: 3520,
    electronegativity: 1.13,
    ionizationEnergy: 527,
    properties: ['Soft', 'Silvery', 'Develops green oxide'],
    uses: ['Magnets', 'Lasers', 'Alloys', 'Arc lighting']
  },
  {
    id: 60,
    symbol: 'Nd',
    name: 'Neodymium',
    atomicNumber: 60,
    atomicWeight: 144.242,
    category: ElementCategory.LANTHANIDES,
    period: 6,
    group: 3,
    block: 'f',
    electronConfiguration: '[Xe] 4f⁴ 6s²',
    description: 'Silvery-white lanthanide metal used in powerful magnets.',
    discoveredBy: 'Carl Auer von Welsbach',
    discoveredYear: 1885,
    color: '#C7FFC7',
    phase: 'solid',
    density: 7.01,
    meltingPoint: 1021,
    boilingPoint: 3074,
    electronegativity: 1.14,
    ionizationEnergy: 533,
    properties: ['Silvery-white', 'Magnetic', 'Tarnishes rapidly'],
    uses: ['Permanent magnets', 'Lasers', 'Glass coloring', 'Alloys']
  },
  {
    id: 61,
    symbol: 'Pm',
    name: 'Promethium',
    atomicNumber: 61,
    atomicWeight: 145,
    category: ElementCategory.LANTHANIDES,
    period: 6,
    group: 3,
    block: 'f',
    electronConfiguration: '[Xe] 4f⁵ 6s²',
    description: 'Radioactive lanthanide metal with no stable isotopes.',
    discoveredBy: 'Charles D. Coryell',
    discoveredYear: 1945,
    color: '#A3FFC7',
    phase: 'solid',
    density: 7.26,
    meltingPoint: 1042,
    boilingPoint: 3000,
    electronegativity: 1.13,
    ionizationEnergy: 540,
    properties: ['Radioactive', 'No stable isotopes', 'Silvery'],
    uses: ['Luminous paint', 'Nuclear batteries', 'Thickness gauges', 'Research']
  },
  {
    id: 62,
    symbol: 'Sm',
    name: 'Samarium',
    atomicNumber: 62,
    atomicWeight: 150.36,
    category: ElementCategory.LANTHANIDES,
    period: 6,
    group: 3,
    block: 'f',
    electronConfiguration: '[Xe] 4f⁶ 6s²',
    description: 'Silvery-white lanthanide metal used in magnets.',
    discoveredBy: 'Paul-Émile Lecoq de Boisbaudran',
    discoveredYear: 1879,
    color: '#8FFFC7',
    phase: 'solid',
    density: 7.52,
    meltingPoint: 1072,
    boilingPoint: 1794,
    electronegativity: 1.17,
    ionizationEnergy: 544,
    properties: ['Silvery-white', 'Hard', 'Brittle'],
    uses: ['Magnets', 'Lasers', 'Nuclear reactors', 'Catalysts']
  },
  {
    id: 63,
    symbol: 'Eu',
    name: 'Europium',
    atomicNumber: 63,
    atomicWeight: 151.964,
    category: ElementCategory.LANTHANIDES,
    period: 6,
    group: 3,
    block: 'f',
    electronConfiguration: '[Xe] 4f⁷ 6s²',
    description: 'Soft, silvery lanthanide metal used in phosphors.',
    discoveredBy: 'Eugène-Anatole Demarçay',
    discoveredYear: 1901,
    color: '#61FFC7',
    phase: 'solid',
    density: 5.24,
    meltingPoint: 822,
    boilingPoint: 1529,
    electronegativity: 1.2,
    ionizationEnergy: 547,
    properties: ['Soft', 'Silvery', 'Most reactive lanthanide'],
    uses: ['Phosphors', 'Lasers', 'Nuclear control rods', 'Alloys']
  },
  {
    id: 64,
    symbol: 'Gd',
    name: 'Gadolinium',
    atomicNumber: 64,
    atomicWeight: 157.25,
    category: ElementCategory.LANTHANIDES,
    period: 6,
    group: 3,
    block: 'f',
    electronConfiguration: '[Xe] 4f⁷ 5d¹ 6s²',
    description: 'Silvery-white lanthanide metal with unique magnetic properties.',
    discoveredBy: 'Jean Charles Galissard de Marignac',
    discoveredYear: 1880,
    color: '#45FFC7',
    phase: 'solid',
    density: 7.9,
    meltingPoint: 1313,
    boilingPoint: 3273,
    electronegativity: 1.2,
    ionizationEnergy: 593,
    properties: ['Silvery-white', 'Magnetic', 'Ductile'],
    uses: ['MRI contrast agents', 'Neutron radiography', 'Magnets', 'Alloys']
  },
  {
    id: 65,
    symbol: 'Tb',
    name: 'Terbium',
    atomicNumber: 65,
    atomicWeight: 158.92535,
    category: ElementCategory.LANTHANIDES,
    period: 6,
    group: 3,
    block: 'f',
    electronConfiguration: '[Xe] 4f⁹ 6s²',
    description: 'Silvery-grey lanthanide metal used in phosphors.',
    discoveredBy: 'Carl Gustaf Mosander',
    discoveredYear: 1843,
    color: '#30FFC7',
    phase: 'solid',
    density: 8.23,
    meltingPoint: 1356,
    boilingPoint: 3230,
    electronegativity: 1.2,
    ionizationEnergy: 565,
    properties: ['Silvery-grey', 'Malleable', 'Ductile'],
    uses: ['Phosphors', 'Lasers', 'Magnets', 'Alloys']
  },
  {
    id: 66,
    symbol: 'Dy',
    name: 'Dysprosium',
    atomicNumber: 66,
    atomicWeight: 162.5,
    category: ElementCategory.LANTHANIDES,
    period: 6,
    group: 3,
    block: 'f',
    electronConfiguration: '[Xe] 4f¹⁰ 6s²',
    description: 'Silvery lanthanide metal with high magnetic susceptibility.',
    discoveredBy: 'Paul-Émile Lecoq de Boisbaudran',
    discoveredYear: 1886,
    color: '#1FFFC7',
    phase: 'solid',
    density: 8.54,
    meltingPoint: 1412,
    boilingPoint: 2567,
    electronegativity: 1.22,
    ionizationEnergy: 573,
    properties: ['Silvery', 'High magnetic susceptibility', 'Hard'],
    uses: ['Magnets', 'Lasers', 'Nuclear reactors', 'Alloys']
  },
  {
    id: 67,
    symbol: 'Ho',
    name: 'Holmium',
    atomicNumber: 67,
    atomicWeight: 164.93032,
    category: ElementCategory.LANTHANIDES,
    period: 6,
    group: 3,
    block: 'f',
    electronConfiguration: '[Xe] 4f¹¹ 6s²',
    description: 'Silvery lanthanide metal with highest magnetic permeability.',
    discoveredBy: 'Per Teodor Cleve',
    discoveredYear: 1878,
    color: '#00FF9C',
    phase: 'solid',
    density: 8.8,
    meltingPoint: 1474,
    boilingPoint: 2700,
    electronegativity: 1.23,
    ionizationEnergy: 581,
    properties: ['Silvery', 'Highest magnetic permeability', 'Soft'],
    uses: ['Magnets', 'Lasers', 'Nuclear reactors', 'Alloys']
  },
  {
    id: 68,
    symbol: 'Er',
    name: 'Erbium',
    atomicNumber: 68,
    atomicWeight: 167.259,
    category: ElementCategory.LANTHANIDES,
    period: 6,
    group: 3,
    block: 'f',
    electronConfiguration: '[Xe] 4f¹² 6s²',
    description: 'Silvery-white lanthanide metal used in fiber optics.',
    discoveredBy: 'Carl Gustaf Mosander',
    discoveredYear: 1843,
    color: '#00E675',
    phase: 'solid',
    density: 9.07,
    meltingPoint: 1529,
    boilingPoint: 2868,
    electronegativity: 1.24,
    ionizationEnergy: 589,
    properties: ['Silvery-white', 'Soft', 'Malleable'],
    uses: ['Fiber optics', 'Lasers', 'Alloys', 'Nuclear technology']
  },
  {
    id: 69,
    symbol: 'Tm',
    name: 'Thulium',
    atomicNumber: 69,
    atomicWeight: 168.93421,
    category: ElementCategory.LANTHANIDES,
    period: 6,
    group: 3,
    block: 'f',
    electronConfiguration: '[Xe] 4f¹³ 6s²',
    description: 'Silvery-grey lanthanide metal, the least abundant rare earth.',
    discoveredBy: 'Per Teodor Cleve',
    discoveredYear: 1879,
    color: '#00D452',
    phase: 'solid',
    density: 9.32,
    meltingPoint: 1545,
    boilingPoint: 1950,
    electronegativity: 1.25,
    ionizationEnergy: 597,
    properties: ['Silvery-grey', 'Soft', 'Least abundant rare earth'],
    uses: ['Portable X-rays', 'Lasers', 'High-temperature superconductors', 'Research']
  },
  {
    id: 70,
    symbol: 'Yb',
    name: 'Ytterbium',
    atomicNumber: 70,
    atomicWeight: 173.054,
    category: ElementCategory.LANTHANIDES,
    period: 6,
    group: 3,
    block: 'f',
    electronConfiguration: '[Xe] 4f¹⁴ 6s²',
    description: 'Soft, malleable lanthanide metal used in alloys.',
    discoveredBy: 'Jean Charles Galissard de Marignac',
    discoveredYear: 1878,
    color: '#00BF38',
    phase: 'solid',
    density: 6.9,
    meltingPoint: 819,
    boilingPoint: 1196,
    electronegativity: 1.1,
    ionizationEnergy: 603,
    properties: ['Soft', 'Malleable', 'Ductile'],
    uses: ['Alloys', 'Lasers', 'Catalysts', 'Stress gauges']
  },
  {
    id: 71,
    symbol: 'Lu',
    name: 'Lutetium',
    atomicNumber: 71,
    atomicWeight: 174.9668,
    category: ElementCategory.LANTHANIDES,
    period: 6,
    group: 3,
    block: 'd',
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹ 6s²',
    description: 'Hard, dense, silvery-white lanthanide metal.',
    discoveredBy: 'Carl Auer von Welsbach',
    discoveredYear: 1907,
    color: '#00AB24',
    phase: 'solid',
    density: 9.84,
    meltingPoint: 1663,
    boilingPoint: 3402,
    electronegativity: 1.27,
    ionizationEnergy: 524,
    properties: ['Hard', 'Dense', 'Silvery-white'],
    uses: ['Catalysts', 'PET scan detectors', 'Research', 'High refractive index glass']
  },
  {
    id: 72,
    symbol: 'Hf',
    name: 'Hafnium',
    atomicNumber: 72,
    atomicWeight: 178.49,
    category: ElementCategory.TRANSITION_METALS,
    period: 6,
    group: 4,
    block: 'd',
    electronConfiguration: '[Xe] 4f¹⁴ 5d² 6s²',
    description: 'Lustrous, silvery-grey transition metal used in nuclear reactors.',
    discoveredBy: 'Dirk Coster',
    discoveredYear: 1923,
    color: '#4DC2FF',
    phase: 'solid',
    density: 13.31,
    meltingPoint: 2233,
    boilingPoint: 4603,
    electronegativity: 1.3,
    ionizationEnergy: 659,
    properties: ['Lustrous', 'Silvery-grey', 'Corrosion-resistant'],
    uses: ['Nuclear reactors', 'Superalloys', 'Plasma cutting', 'Semiconductors']
  },
  {
    id: 73,
    symbol: 'Ta',
    name: 'Tantalum',
    atomicNumber: 73,
    atomicWeight: 180.94788,
    category: ElementCategory.TRANSITION_METALS,
    period: 6,
    group: 5,
    block: 'd',
    electronConfiguration: '[Xe] 4f¹⁴ 5d³ 6s²',
    description: 'Hard, blue-grey transition metal used in capacitors.',
    discoveredBy: 'Anders Gustaf Ekeberg',
    discoveredYear: 1802,
    color: '#4DA6FF',
    phase: 'solid',
    density: 16.65,
    meltingPoint: 3017,
    boilingPoint: 5458,
    electronegativity: 1.5,
    ionizationEnergy: 761,
    properties: ['Hard', 'Blue-grey', 'Corrosion-resistant'],
    uses: ['Capacitors', 'Superalloys', 'Chemical equipment', 'Medical implants']
  },
  {
    id: 74,
    symbol: 'W',
    name: 'Tungsten',
    atomicNumber: 74,
    atomicWeight: 183.84,
    category: ElementCategory.TRANSITION_METALS,
    period: 6,
    group: 6,
    block: 'd',
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁴ 6s²',
    description: 'Greyish-white metal with highest melting point.',
    discoveredBy: 'Juan José Elhuyar',
    discoveredYear: 1783,
    color: '#2194D6',
    phase: 'solid',
    density: 19.25,
    meltingPoint: 3695,
    boilingPoint: 5828,
    electronegativity: 2.36,
    ionizationEnergy: 770,
    properties: ['Highest melting point', 'Hard', 'Dense'],
    uses: ['Light bulb filaments', 'Alloys', 'Radiation shielding', 'Cutting tools']
  },
  {
    id: 75,
    symbol: 'Re',
    name: 'Rhenium',
    atomicNumber: 75,
    atomicWeight: 186.207,
    category: ElementCategory.TRANSITION_METALS,
    period: 6,
    group: 7,
    block: 'd',
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁵ 6s²',
    description: 'Silvery-white metal with third-highest melting point.',
    discoveredBy: 'Ida Tacke',
    discoveredYear: 1925,
    color: '#267DAB',
    phase: 'solid',
    density: 21.02,
    meltingPoint: 3459,
    boilingPoint: 5869,
    electronegativity: 1.9,
    ionizationEnergy: 760,
    properties: ['Silvery-white', 'Third-highest melting point', 'Dense'],
    uses: ['Superalloys', 'Catalysts', 'Thermocouples', 'Jet engines']
  },
  {
    id: 76,
    symbol: 'Os',
    name: 'Osmium',
    atomicNumber: 76,
    atomicWeight: 190.23,
    category: ElementCategory.TRANSITION_METALS,
    period: 6,
    group: 8,
    block: 'd',
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁶ 6s²',
    description: 'Hard, brittle, bluish-white metal with highest density.',
    discoveredBy: 'Smithson Tennant',
    discoveredYear: 1803,
    color: '#266696',
    phase: 'solid',
    density: 22.59,
    meltingPoint: 3033,
    boilingPoint: 5012,
    electronegativity: 2.2,
    ionizationEnergy: 840,
    properties: ['Highest density', 'Hard', 'Brittle'],
    uses: ['Fountain pen tips', 'Electrical contacts', 'Alloys', 'Catalysts']
  },
  {
    id: 77,
    symbol: 'Ir',
    name: 'Iridium',
    atomicNumber: 77,
    atomicWeight: 192.217,
    category: ElementCategory.TRANSITION_METALS,
    period: 6,
    group: 9,
    block: 'd',
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁷ 6s²',
    description: 'Hard, brittle, silvery-white metal, most corrosion-resistant.',
    discoveredBy: 'Smithson Tennant',
    discoveredYear: 1803,
    color: '#175487',
    phase: 'solid',
    density: 22.42,
    meltingPoint: 2466,
    boilingPoint: 4428,
    electronegativity: 2.2,
    ionizationEnergy: 880,
    properties: ['Most corrosion-resistant', 'Hard', 'Brittle'],
    uses: ['Spark plugs', 'Crucibles', 'Electrical contacts', 'Catalysts']
  },
  {
    id: 78,
    symbol: 'Pt',
    name: 'Platinum',
    atomicNumber: 78,
    atomicWeight: 195.084,
    category: ElementCategory.TRANSITION_METALS,
    period: 6,
    group: 10,
    block: 'd',
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁹ 6s¹',
    description: 'Dense, malleable, silvery-white precious metal.',
    discoveredBy: 'Antonio de Ulloa',
    discoveredYear: 1735,
    color: '#D0D0E0',
    phase: 'solid',
    density: 21.45,
    meltingPoint: 1768.2,
    boilingPoint: 3825,
    electronegativity: 2.28,
    ionizationEnergy: 870,
    properties: ['Dense', 'Malleable', 'Precious metal'],
    uses: ['Jewelry', 'Catalysts', 'Laboratory equipment', 'Cancer treatment']
  },
  {
    id: 79,
    symbol: 'Au',
    name: 'Gold',
    atomicNumber: 79,
    atomicWeight: 196.97,
    category: ElementCategory.TRANSITION_METALS,
    period: 6,
    group: 11,
    block: 'd',
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹',
    description: 'Precious metal, excellent conductor, corrosion-resistant.',
    discoveredBy: 'Ancient civilizations',
    discoveredYear: -2600,
    color: '#FFD123',
    phase: 'solid',
    density: 19.3,
    meltingPoint: 1064,
    boilingPoint: 2856,
    electronegativity: 2.54,
    ionizationEnergy: 890,
    properties: ['Precious', 'Corrosion-resistant', 'Malleable'],
    uses: ['Jewelry', 'Electronics', 'Dentistry', 'Currency']
  },
  {
    id: 80,
    symbol: 'Hg',
    name: 'Mercury',
    atomicNumber: 80,
    atomicWeight: 200.59,
    category: ElementCategory.TRANSITION_METALS,
    period: 6,
    group: 12,
    block: 'd',
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s²',
    description: 'Only liquid metal at room temperature, toxic.',
    discoveredBy: 'Ancient civilizations',
    discoveredYear: -1500,
    color: '#B8B8D0',
    phase: 'liquid',
    density: 13.53,
    meltingPoint: -38.8,
    boilingPoint: 357,
    electronegativity: 2.00,
    ionizationEnergy: 1007,
    properties: ['Liquid at room temperature', 'Toxic', 'Dense'],
    uses: ['Thermometers', 'Barometers', 'Dental amalgam', 'Fluorescent lamps']
  },
  {
    id: 81,
    symbol: 'Tl',
    name: 'Thallium',
    atomicNumber: 81,
    atomicWeight: 204.3833,
    category: ElementCategory.POST_TRANSITION_METALS,
    period: 6,
    group: 13,
    block: 'p',
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹',
    description: 'Soft, grey post-transition metal that is highly toxic.',
    discoveredBy: 'William Crookes',
    discoveredYear: 1861,
    color: '#A6544D',
    phase: 'solid',
    density: 11.85,
    meltingPoint: 304,
    boilingPoint: 1473,
    electronegativity: 1.62,
    ionizationEnergy: 589,
    properties: ['Soft', 'Grey', 'Highly toxic'],
    uses: ['Electronics', 'Optics', 'Rat poison', 'Alloys']
  },
  {
    id: 82,
    symbol: 'Pb',
    name: 'Lead',
    atomicNumber: 82,
    atomicWeight: 207.2,
    category: ElementCategory.POST_TRANSITION_METALS,
    period: 6,
    group: 14,
    block: 'p',
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²',
    description: 'Heavy, soft, malleable metal with bluish-white color.',
    discoveredBy: 'Ancient civilizations',
    discoveredYear: -7000,
    color: '#575961',
    phase: 'solid',
    density: 11.34,
    meltingPoint: 327.46,
    boilingPoint: 1749,
    electronegativity: 1.87,
    ionizationEnergy: 716,
    properties: ['Heavy', 'Soft', 'Malleable'],
    uses: ['Batteries', 'Radiation shielding', 'Ammunition', 'Roofing']
  },
  {
    id: 83,
    symbol: 'Bi',
    name: 'Bismuth',
    atomicNumber: 83,
    atomicWeight: 208.9804,
    category: ElementCategory.POST_TRANSITION_METALS,
    period: 6,
    group: 15,
    block: 'p',
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³',
    description: 'Brittle, crystalline metal with iridescent appearance.',
    discoveredBy: 'Claude François Geoffroy',
    discoveredYear: 1753,
    color: '#9E4FB5',
    phase: 'solid',
    density: 9.78,
    meltingPoint: 271.4,
    boilingPoint: 1564,
    electronegativity: 2.02,
    ionizationEnergy: 703,
    properties: ['Brittle', 'Crystalline', 'Iridescent'],
    uses: ['Cosmetics', 'Alloys', 'Medicine', 'Fire detectors']
  },
  {
    id: 84,
    symbol: 'Po',
    name: 'Polonium',
    atomicNumber: 84,
    atomicWeight: 209,
    category: ElementCategory.POST_TRANSITION_METALS,
    period: 6,
    group: 16,
    block: 'p',
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴',
    description: 'Rare, highly radioactive metal discovered by Marie Curie.',
    discoveredBy: 'Marie Curie',
    discoveredYear: 1898,
    color: '#AB5C00',
    phase: 'solid',
    density: 9.2,
    meltingPoint: 254,
    boilingPoint: 962,
    electronegativity: 2.0,
    ionizationEnergy: 812,
    properties: ['Rare', 'Highly radioactive', 'Silvery'],
    uses: ['Nuclear batteries', 'Neutron sources', 'Antistatic devices', 'Research']
  },
  {
    id: 85,
    symbol: 'At',
    name: 'Astatine',
    atomicNumber: 85,
    atomicWeight: 210,
    category: ElementCategory.HALOGENS,
    period: 6,
    group: 17,
    block: 'p',
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵',
    description: 'Rarest naturally occurring halogen, highly radioactive.',
    discoveredBy: 'Dale R. Corson',
    discoveredYear: 1940,
    color: '#754F45',
    phase: 'solid',
    density: 7,
    meltingPoint: 302,
    boilingPoint: 337,
    electronegativity: 2.2,
    ionizationEnergy: 920,
    properties: ['Rarest natural halogen', 'Highly radioactive', 'Metallic'],
    uses: ['Cancer treatment', 'Research', 'No commercial uses']
  },
  {
    id: 86,
    symbol: 'Rn',
    name: 'Radon',
    atomicNumber: 86,
    atomicWeight: 222,
    category: ElementCategory.NOBLE_GASES,
    period: 6,
    group: 18,
    block: 'p',
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶',
    description: 'Radioactive noble gas that accumulates in buildings.',
    discoveredBy: 'Friedrich Ernst Dorn',
    discoveredYear: 1900,
    color: '#428296',
    phase: 'gas',
    density: 9.73,
    meltingPoint: -71,
    boilingPoint: -62,
    electronegativity: 2.2,
    ionizationEnergy: 1037,
    properties: ['Radioactive', 'Noble gas', 'Colorless'],
    uses: ['Cancer treatment', 'Earthquake prediction', 'Research']
  },

  // Period 7 and synthetic elements
  {
    id: 87,
    symbol: 'Fr',
    name: 'Francium',
    atomicNumber: 87,
    atomicWeight: 223,
    category: ElementCategory.ALKALI_METALS,
    period: 7,
    group: 1,
    block: 's',
    electronConfiguration: '[Rn] 7s¹',
    description: 'Highly radioactive, rarest naturally occurring element.',
    discoveredBy: 'Marguerite Perey',
    discoveredYear: 1939,
    color: '#420066',
    phase: 'solid',
    density: 1.87,
    meltingPoint: 27,
    boilingPoint: 677,
    electronegativity: 0.7,
    ionizationEnergy: 380,
    properties: ['Highly radioactive', 'Rarest natural element', 'Alkali metal'],
    uses: ['Research', 'No commercial uses due to radioactivity']
  },
  {
    id: 88,
    symbol: 'Ra',
    name: 'Radium',
    atomicNumber: 88,
    atomicWeight: 226,
    category: ElementCategory.ALKALINE_EARTH_METALS,
    period: 7,
    group: 2,
    block: 's',
    electronConfiguration: '[Rn] 7s²',
    description: 'Highly radioactive alkaline earth metal that glows in the dark.',
    discoveredBy: 'Marie Curie',
    discoveredYear: 1898,
    color: '#007D00',
    phase: 'solid',
    density: 5.5,
    meltingPoint: 696,
    boilingPoint: 1737,
    electronegativity: 0.9,
    ionizationEnergy: 509,
    properties: ['Highly radioactive', 'Glows in dark', 'Alkaline earth metal'],
    uses: ['Cancer treatment', 'Luminous paints', 'Neutron sources', 'Research']
  },
  {
    id: 89,
    symbol: 'Ac',
    name: 'Actinium',
    atomicNumber: 89,
    atomicWeight: 227,
    category: ElementCategory.ACTINIDES,
    period: 7,
    group: 3,
    block: 'd',
    electronConfiguration: '[Rn] 6d¹ 7s²',
    description: 'Radioactive actinide metal that glows blue in the dark.',
    discoveredBy: 'André-Louis Debierne',
    discoveredYear: 1899,
    color: '#70ABFA',
    phase: 'solid',
    density: 10.07,
    meltingPoint: 1051,
    boilingPoint: 3198,
    electronegativity: 1.1,
    ionizationEnergy: 499,
    properties: ['Radioactive', 'Glows blue', 'Silvery-white'],
    uses: ['Neutron sources', 'Cancer treatment', 'Research']
  },
  {
    id: 90,
    symbol: 'Th',
    name: 'Thorium',
    atomicNumber: 90,
    atomicWeight: 232.0377,
    category: ElementCategory.ACTINIDES,
    period: 7,
    group: 3,
    block: 'f',
    electronConfiguration: '[Rn] 6d² 7s²',
    description: 'Radioactive actinide metal used in nuclear reactors.',
    discoveredBy: 'Jöns Jacob Berzelius',
    discoveredYear: 1828,
    color: '#00BAFF',
    phase: 'solid',
    density: 11.7,
    meltingPoint: 1750,
    boilingPoint: 4788,
    electronegativity: 1.3,
    ionizationEnergy: 587,
    properties: ['Radioactive', 'Silvery-white', 'Ductile'],
    uses: ['Nuclear reactors', 'Mantles', 'Welding electrodes', 'Catalysts']
  },
  {
    id: 91,
    symbol: 'Pa',
    name: 'Protactinium',
    atomicNumber: 91,
    atomicWeight: 231.0359,
    category: ElementCategory.ACTINIDES,
    period: 7,
    group: 3,
    block: 'f',
    electronConfiguration: '[Rn] 5f² 6d¹ 7s²',
    description: 'Rare, radioactive actinide metal with silvery-metallic luster.',
    discoveredBy: 'Otto Hahn',
    discoveredYear: 1917,
    color: '#00A1FF',
    phase: 'solid',
    density: 15.37,
    meltingPoint: 1572,
    boilingPoint: 4000,
    electronegativity: 1.5,
    ionizationEnergy: 568,
    properties: ['Rare', 'Radioactive', 'Silvery-metallic'],
    uses: ['Research', 'Nuclear dating', 'No commercial uses']
  },
  {
    id: 92,
    symbol: 'U',
    name: 'Uranium',
    atomicNumber: 92,
    atomicWeight: 238.03,
    category: ElementCategory.ACTINIDES,
    period: 7,
    group: 3,
    block: 'f',
    electronConfiguration: '[Rn] 5f³ 6d¹ 7s²',
    description: 'Radioactive element used in nuclear power and weapons.',
    discoveredBy: 'Martin Heinrich Klaproth',
    discoveredYear: 1789,
    color: '#008F00',
    phase: 'solid',
    density: 19.1,
    meltingPoint: 1135,
    boilingPoint: 4131,
    electronegativity: 1.38,
    ionizationEnergy: 598,
    properties: ['Radioactive', 'Heavy', 'Silvery-gray'],
    uses: ['Nuclear power', 'Nuclear weapons', 'Dating rocks', 'Glass coloring']
  },
  {
    id: 93,
    symbol: 'Np',
    name: 'Neptunium',
    atomicNumber: 93,
    atomicWeight: 237,
    category: ElementCategory.ACTINIDES,
    period: 7,
    group: 3,
    block: 'f',
    electronConfiguration: '[Rn] 5f⁴ 6d¹ 7s²',
    description: 'First transuranium element, radioactive and silvery.',
    discoveredBy: 'Edwin McMillan',
    discoveredYear: 1940,
    color: '#0080FF',
    phase: 'solid',
    density: 20.2,
    meltingPoint: 644,
    boilingPoint: 4174,
    electronegativity: 1.36,
    ionizationEnergy: 604,
    properties: ['First transuranium', 'Radioactive', 'Silvery'],
    uses: ['Nuclear reactors', 'Neutron detection', 'Research']
  },
  {
    id: 94,
    symbol: 'Pu',
    name: 'Plutonium',
    atomicNumber: 94,
    atomicWeight: 244,
    category: ElementCategory.ACTINIDES,
    period: 7,
    group: 3,
    block: 'f',
    electronConfiguration: '[Rn] 5f⁶ 7s²',
    description: 'Radioactive actinide used in nuclear weapons and reactors.',
    discoveredBy: 'Glenn T. Seaborg',
    discoveredYear: 1940,
    color: '#006BFF',
    phase: 'solid',
    density: 19.8,
    meltingPoint: 640,
    boilingPoint: 3228,
    electronegativity: 1.28,
    ionizationEnergy: 584,
    properties: ['Radioactive', 'Fissile', 'Silvery-white'],
    uses: ['Nuclear weapons', 'Nuclear reactors', 'Space missions', 'Research']
  },
  {
    id: 95,
    symbol: 'Am',
    name: 'Americium',
    atomicNumber: 95,
    atomicWeight: 243,
    category: ElementCategory.ACTINIDES,
    period: 7,
    group: 3,
    block: 'f',
    electronConfiguration: '[Rn] 5f⁷ 7s²',
    description: 'Radioactive actinide used in smoke detectors.',
    discoveredBy: 'Glenn T. Seaborg',
    discoveredYear: 1944,
    color: '#545CF2',
    phase: 'solid',
    density: 13.69,
    meltingPoint: 1176,
    boilingPoint: 2011,
    electronegativity: 1.3,
    ionizationEnergy: 578,
    properties: ['Radioactive', 'Silvery-white', 'Tarnishes slowly'],
    uses: ['Smoke detectors', 'Neutron sources', 'Research']
  },
  {
    id: 96,
    symbol: 'Cm',
    name: 'Curium',
    atomicNumber: 96,
    atomicWeight: 247,
    category: ElementCategory.ACTINIDES,
    period: 7,
    group: 3,
    block: 'f',
    electronConfiguration: '[Rn] 5f⁷ 6d¹ 7s²',
    description: 'Radioactive actinide that glows purple in the dark.',
    discoveredBy: 'Glenn T. Seaborg',
    discoveredYear: 1944,
    color: '#785CE3',
    phase: 'solid',
    density: 13.51,
    meltingPoint: 1345,
    boilingPoint: 3110,
    electronegativity: 1.3,
    ionizationEnergy: 581,
    properties: ['Radioactive', 'Glows purple', 'Silvery-white'],
    uses: ['Radioisotope thermoelectric generators', 'Research', 'Space missions']
  },
  {
    id: 97,
    symbol: 'Bk',
    name: 'Berkelium',
    atomicNumber: 97,
    atomicWeight: 247,
    category: ElementCategory.ACTINIDES,
    period: 7,
    group: 3,
    block: 'f',
    electronConfiguration: '[Rn] 5f⁹ 7s²',
    description: 'Radioactive actinide with silvery appearance.',
    discoveredBy: 'Glenn T. Seaborg',
    discoveredYear: 1949,
    color: '#8A4FE3',
    phase: 'solid',
    density: 14.79,
    meltingPoint: 1050,
    boilingPoint: 2627,
    electronegativity: 1.3,
    ionizationEnergy: 601,
    properties: ['Radioactive', 'Silvery', 'Soft'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 98,
    symbol: 'Cf',
    name: 'Californium',
    atomicNumber: 98,
    atomicWeight: 251,
    category: ElementCategory.ACTINIDES,
    period: 7,
    group: 3,
    block: 'f',
    electronConfiguration: '[Rn] 5f¹⁰ 7s²',
    description: 'Radioactive actinide used in neutron sources.',
    discoveredBy: 'Glenn T. Seaborg',
    discoveredYear: 1950,
    color: '#A136D4',
    phase: 'solid',
    density: 15.1,
    meltingPoint: 900,
    boilingPoint: 1743,
    electronegativity: 1.3,
    ionizationEnergy: 608,
    properties: ['Radioactive', 'Silvery-white', 'Malleable'],
    uses: ['Neutron sources', 'Cancer treatment', 'Nuclear reactors', 'Research']
  },
  {
    id: 99,
    symbol: 'Es',
    name: 'Einsteinium',
    atomicNumber: 99,
    atomicWeight: 252,
    category: ElementCategory.ACTINIDES,
    period: 7,
    group: 3,
    block: 'f',
    electronConfiguration: '[Rn] 5f¹¹ 7s²',
    description: 'Radioactive actinide with very short half-life.',
    discoveredBy: 'Albert Ghiorso',
    discoveredYear: 1952,
    color: '#B31FD4',
    phase: 'solid',
    density: 8.84,
    meltingPoint: 860,
    boilingPoint: 1130,
    electronegativity: 1.3,
    ionizationEnergy: 619,
    properties: ['Radioactive', 'Short half-life', 'Silvery'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 100,
    symbol: 'Fm',
    name: 'Fermium',
    atomicNumber: 100,
    atomicWeight: 257,
    category: ElementCategory.ACTINIDES,
    period: 7,
    group: 3,
    block: 'f',
    electronConfiguration: '[Rn] 5f¹² 7s²',
    description: 'Radioactive actinide with extremely short half-life.',
    discoveredBy: 'Albert Ghiorso',
    discoveredYear: 1952,
    color: '#B31FBA',
    phase: 'solid',
    density: 9.7,
    meltingPoint: 1527,
    boilingPoint: 1800,
    electronegativity: 1.3,
    ionizationEnergy: 627,
    properties: ['Radioactive', 'Extremely short half-life', 'Synthetic'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 101,
    symbol: 'Md',
    name: 'Mendelevium',
    atomicNumber: 101,
    atomicWeight: 258,
    category: ElementCategory.ACTINIDES,
    period: 7,
    group: 3,
    block: 'f',
    electronConfiguration: '[Rn] 5f¹³ 7s²',
    description: 'Radioactive actinide named after Dmitri Mendeleev.',
    discoveredBy: 'Albert Ghiorso',
    discoveredYear: 1955,
    color: '#B30DA6',
    phase: 'solid',
    density: 10.3,
    meltingPoint: 827,
    boilingPoint: 1100,
    electronegativity: 1.3,
    ionizationEnergy: 635,
    properties: ['Radioactive', 'Synthetic', 'Metallic'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 102,
    symbol: 'No',
    name: 'Nobelium',
    atomicNumber: 102,
    atomicWeight: 259,
    category: ElementCategory.ACTINIDES,
    period: 7,
    group: 3,
    block: 'f',
    electronConfiguration: '[Rn] 5f¹⁴ 7s²',
    description: 'Radioactive actinide named after Alfred Nobel.',
    discoveredBy: 'Albert Ghiorso',
    discoveredYear: 1958,
    color: '#BD0D87',
    phase: 'solid',
    density: 9.9,
    meltingPoint: 827,
    boilingPoint: 1100,
    electronegativity: 1.3,
    ionizationEnergy: 642,
    properties: ['Radioactive', 'Synthetic', 'Metallic'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 103,
    symbol: 'Lr',
    name: 'Lawrencium',
    atomicNumber: 103,
    atomicWeight: 262,
    category: ElementCategory.ACTINIDES,
    period: 7,
    group: 3,
    block: 'd',
    electronConfiguration: '[Rn] 5f¹⁴ 7s² 7p¹',
    description: 'Radioactive actinide, last element in the actinide series.',
    discoveredBy: 'Albert Ghiorso',
    discoveredYear: 1961,
    color: '#C70066',
    phase: 'solid',
    density: 15.6,
    meltingPoint: 1627,
    boilingPoint: 1900,
    electronegativity: 1.3,
    ionizationEnergy: 470,
    properties: ['Radioactive', 'Last actinide', 'Synthetic'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 104,
    symbol: 'Rf',
    name: 'Rutherfordium',
    atomicNumber: 104,
    atomicWeight: 267,
    category: ElementCategory.TRANSITION_METALS,
    period: 7,
    group: 4,
    block: 'd',
    electronConfiguration: '[Rn] 5f¹⁴ 6d² 7s²',
    description: 'Synthetic superheavy transition metal.',
    discoveredBy: 'Albert Ghiorso',
    discoveredYear: 1964,
    color: '#CC0059',
    phase: 'solid',
    density: 18.1,
    meltingPoint: 2100,
    boilingPoint: 5500,
    electronegativity: 1.3,
    ionizationEnergy: 580,
    properties: ['Synthetic', 'Superheavy', 'Radioactive'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 105,
    symbol: 'Db',
    name: 'Dubnium',
    atomicNumber: 105,
    atomicWeight: 268,
    category: ElementCategory.TRANSITION_METALS,
    period: 7,
    group: 5,
    block: 'd',
    electronConfiguration: '[Rn] 5f¹⁴ 6d³ 7s²',
    description: 'Synthetic superheavy transition metal.',
    discoveredBy: 'Albert Ghiorso',
    discoveredYear: 1967,
    color: '#D1004F',
    phase: 'solid',
    density: 21.6,
    meltingPoint: 2900,
    boilingPoint: 6000,
    electronegativity: 1.5,
    ionizationEnergy: 665,
    properties: ['Synthetic', 'Superheavy', 'Radioactive'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 106,
    symbol: 'Sg',
    name: 'Seaborgium',
    atomicNumber: 106,
    atomicWeight: 271,
    category: ElementCategory.TRANSITION_METALS,
    period: 7,
    group: 6,
    block: 'd',
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁴ 7s²',
    description: 'Synthetic superheavy transition metal named after Glenn Seaborg.',
    discoveredBy: 'Albert Ghiorso',
    discoveredYear: 1974,
    color: '#D90045',
    phase: 'solid',
    density: 23.22,
    meltingPoint: 3200,
    boilingPoint: 6500,
    electronegativity: 1.9,
    ionizationEnergy: 757,
    properties: ['Synthetic', 'Superheavy', 'Radioactive'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 107,
    symbol: 'Bh',
    name: 'Bohrium',
    atomicNumber: 107,
    atomicWeight: 272,
    category: ElementCategory.TRANSITION_METALS,
    period: 7,
    group: 7,
    block: 'd',
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁵ 7s²',
    description: 'Synthetic superheavy transition metal named after Niels Bohr.',
    discoveredBy: 'Peter Armbruster',
    discoveredYear: 1981,
    color: '#E00038',
    phase: 'solid',
    density: 24.5,
    meltingPoint: 3500,
    boilingPoint: 7000,
    electronegativity: 2.0,
    ionizationEnergy: 740,
    properties: ['Synthetic', 'Superheavy', 'Radioactive'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 108,
    symbol: 'Hs',
    name: 'Hassium',
    atomicNumber: 108,
    atomicWeight: 270,
    category: ElementCategory.TRANSITION_METALS,
    period: 7,
    group: 8,
    block: 'd',
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁶ 7s²',
    description: 'Synthetic superheavy transition metal named after the German state Hesse.',
    discoveredBy: 'Peter Armbruster',
    discoveredYear: 1984,
    color: '#E6002E',
    phase: 'solid',
    density: 26,
    meltingPoint: 3800,
    boilingPoint: 7500,
    electronegativity: 2.2,
    ionizationEnergy: 760,
    properties: ['Synthetic', 'Superheavy', 'Radioactive'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 109,
    symbol: 'Mt',
    name: 'Meitnerium',
    atomicNumber: 109,
    atomicWeight: 276,
    category: ElementCategory.TRANSITION_METALS,
    period: 7,
    group: 9,
    block: 'd',
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁷ 7s²',
    description: 'Synthetic superheavy transition metal named after Lise Meitner.',
    discoveredBy: 'Peter Armbruster',
    discoveredYear: 1982,
    color: '#EB0026',
    phase: 'solid',
    density: 27.5,
    meltingPoint: 4100,
    boilingPoint: 8000,
    electronegativity: 2.3,
    ionizationEnergy: 800,
    properties: ['Synthetic', 'Superheavy', 'Radioactive'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 110,
    symbol: 'Ds',
    name: 'Darmstadtium',
    atomicNumber: 110,
    atomicWeight: 281,
    category: ElementCategory.TRANSITION_METALS,
    period: 7,
    group: 10,
    block: 'd',
    electronConfiguration: '[Rn] 5f¹⁴ 6d⁹ 7s¹',
    description: 'Synthetic superheavy transition metal named after Darmstadt.',
    discoveredBy: 'Peter Armbruster',
    discoveredYear: 1994,
    color: '#F00000',
    phase: 'solid',
    density: 26.8,
    meltingPoint: 4400,
    boilingPoint: 8500,
    electronegativity: 2.4,
    ionizationEnergy: 960,
    properties: ['Synthetic', 'Superheavy', 'Radioactive'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 111,
    symbol: 'Rg',
    name: 'Roentgenium',
    atomicNumber: 111,
    atomicWeight: 282,
    category: ElementCategory.TRANSITION_METALS,
    period: 7,
    group: 11,
    block: 'd',
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s¹',
    description: 'Synthetic superheavy transition metal named after Wilhelm Roentgen.',
    discoveredBy: 'Peter Armbruster',
    discoveredYear: 1994,
    color: '#F50000',
    phase: 'solid',
    density: 28.7,
    meltingPoint: 4700,
    boilingPoint: 9000,
    electronegativity: 2.5,
    ionizationEnergy: 1020,
    properties: ['Synthetic', 'Superheavy', 'Radioactive'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 112,
    symbol: 'Cn',
    name: 'Copernicium',
    atomicNumber: 112,
    atomicWeight: 285,
    category: ElementCategory.TRANSITION_METALS,
    period: 7,
    group: 12,
    block: 'd',
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s²',
    description: 'Synthetic superheavy transition metal named after Nicolaus Copernicus.',
    discoveredBy: 'Sigurd Hofmann',
    discoveredYear: 1996,
    color: '#FA0000',
    phase: 'solid',
    density: 23.7,
    meltingPoint: 5000,
    boilingPoint: 9500,
    electronegativity: 2.6,
    ionizationEnergy: 1155,
    properties: ['Synthetic', 'Superheavy', 'Radioactive'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 113,
    symbol: 'Nh',
    name: 'Nihonium',
    atomicNumber: 113,
    atomicWeight: 286,
    category: ElementCategory.POST_TRANSITION_METALS,
    period: 7,
    group: 13,
    block: 'p',
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹',
    description: 'Synthetic superheavy post-transition metal named after Japan.',
    discoveredBy: 'Kosuke Morita',
    discoveredYear: 2004,
    color: '#FF0000',
    phase: 'solid',
    density: 16,
    meltingPoint: 700,
    boilingPoint: 1400,
    electronegativity: 2.1,
    ionizationEnergy: 704,
    properties: ['Synthetic', 'Superheavy', 'Radioactive'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 114,
    symbol: 'Fl',
    name: 'Flerovium',
    atomicNumber: 114,
    atomicWeight: 289,
    category: ElementCategory.POST_TRANSITION_METALS,
    period: 7,
    group: 14,
    block: 'p',
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²',
    description: 'Synthetic superheavy post-transition metal named after Georgy Flerov.',
    discoveredBy: 'Yuri Oganessian',
    discoveredYear: 1999,
    color: '#FF1A00',
    phase: 'solid',
    density: 14,
    meltingPoint: 340,
    boilingPoint: 420,
    electronegativity: 2.2,
    ionizationEnergy: 832,
    properties: ['Synthetic', 'Superheavy', 'Radioactive'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 115,
    symbol: 'Mc',
    name: 'Moscovium',
    atomicNumber: 115,
    atomicWeight: 290,
    category: ElementCategory.POST_TRANSITION_METALS,
    period: 7,
    group: 15,
    block: 'p',
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³',
    description: 'Synthetic superheavy post-transition metal named after Moscow.',
    discoveredBy: 'Yuri Oganessian',
    discoveredYear: 2003,
    color: '#FF3300',
    phase: 'solid',
    density: 13.5,
    meltingPoint: 670,
    boilingPoint: 1400,
    electronegativity: 2.3,
    ionizationEnergy: 538,
    properties: ['Synthetic', 'Superheavy', 'Radioactive'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 116,
    symbol: 'Lv',
    name: 'Livermorium',
    atomicNumber: 116,
    atomicWeight: 293,
    category: ElementCategory.POST_TRANSITION_METALS,
    period: 7,
    group: 16,
    block: 'p',
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴',
    description: 'Synthetic superheavy post-transition metal named after Livermore.',
    discoveredBy: 'Yuri Oganessian',
    discoveredYear: 2000,
    color: '#FF4D00',
    phase: 'solid',
    density: 12.9,
    meltingPoint: 708,
    boilingPoint: 1085,
    electronegativity: 2.4,
    ionizationEnergy: 663,
    properties: ['Synthetic', 'Superheavy', 'Radioactive'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 117,
    symbol: 'Ts',
    name: 'Tennessine',
    atomicNumber: 117,
    atomicWeight: 294,
    category: ElementCategory.HALOGENS,
    period: 7,
    group: 17,
    block: 'p',
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵',
    description: 'Synthetic superheavy halogen named after Tennessee.',
    discoveredBy: 'Yuri Oganessian',
    discoveredYear: 2010,
    color: '#FF6600',
    phase: 'solid',
    density: 7.2,
    meltingPoint: 723,
    boilingPoint: 883,
    electronegativity: 2.5,
    ionizationEnergy: 742,
    properties: ['Synthetic', 'Superheavy', 'Radioactive'],
    uses: ['Research', 'Synthesis of heavier elements']
  },
  {
    id: 118,
    symbol: 'Og',
    name: 'Oganesson',
    atomicNumber: 118,
    atomicWeight: 294,
    category: ElementCategory.NOBLE_GASES,
    period: 7,
    group: 18,
    block: 'p',
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶',
    description: 'Synthetic, superheavy element with very short half-life.',
    discoveredBy: 'Joint Institute for Nuclear Research',
    discoveredYear: 2002,
    color: '#C0C0C0',
    phase: 'solid',
    density: 4.9,
    properties: ['Synthetic', 'Superheavy', 'Radioactive'],
    uses: ['Research only', 'No practical applications']
  }
];

// Element categories with their properties
export const ELEMENT_CATEGORIES = {
  [ElementCategory.ALKALI_METALS]: {
    name: 'Alkali Metals',
    color: '#ab5cf2',
    description: 'Highly reactive metals with one electron in outer shell'
  },
  [ElementCategory.ALKALINE_EARTH_METALS]: {
    name: 'Alkaline Earth Metals',
    color: '#8aff00',
    description: 'Reactive metals with two electrons in outer shell'
  },
  [ElementCategory.TRANSITION_METALS]: {
    name: 'Transition Metals',
    color: '#e06633',
    description: 'Metals with partially filled d orbitals'
  },
  [ElementCategory.POST_TRANSITION_METALS]: {
    name: 'Post-Transition Metals',
    color: '#bfa6a6',
    description: 'Metals that are softer and have lower melting points'
  },
  [ElementCategory.METALLOIDS]: {
    name: 'Metalloids',
    color: '#f0c8a0',
    description: 'Elements with properties between metals and nonmetals'
  },
  [ElementCategory.NONMETALS]: {
    name: 'Nonmetals',
    color: '#ff8000',
    description: 'Elements that are poor conductors of heat and electricity'
  },
  [ElementCategory.HALOGENS]: {
    name: 'Halogens',
    color: '#90e050',
    description: 'Highly reactive nonmetals with seven electrons in outer shell'
  },
  [ElementCategory.NOBLE_GASES]: {
    name: 'Noble Gases',
    color: '#b3e3f5',
    description: 'Inert gases with complete electron shells'
  },
  [ElementCategory.LANTHANIDES]: {
    name: 'Lanthanides',
    color: '#70d4ff',
    description: 'Rare earth elements with f orbitals'
  },
  [ElementCategory.ACTINIDES]: {
    name: 'Actinides',
    color: '#70abfa',
    description: 'Radioactive elements with f orbitals'
  }
};

export const PERIODIC_TABLE_LAYOUT = {
  periods: 7,
  groups: 18,
  lanthanideRow: 8,
  actinideRow: 9
};
